### ISSUE TITLE
data.table benchmark有要講嘛？

### ISSUE THREAD

**Issue by whizzalan** [suensummit/RCourseBankSinoPac#10]
他有幾個問題。
1. 測試code時間太久，建議要講究直接放在markdown中，必且將測試過得結果呈現出來，並解釋讓學員感受到他的力量。
2. 測試code的套件，目前沒有請學員安裝，所以學員基本上無法跟著老師操作，這部份，建議告知同學，或是把安裝套件的指令也涵蓋進去講義中。

``` r
install.packages(c("rbenchmark","plyr"))
```

**Comment by whizzalan** [comment]
![screenshot from 2016-01-03 16-18-19](https://cloud.githubusercontent.com/assets/5684420/12077924/48a07162-b236-11e5-9775-a734523d1bb8.png)

這是我測試的結果，跑超久的...我sample size N=30000

**Comment by suensummit** [comment]
上次我自己跑完 benchmark 之後也覺得太花時間，而且對他們來說效果不顯著，因此 `data.table` 後來決定不講。（純延伸閱讀）
