### ISSUE TITLE
Problem of readLines

### ISSUE THREAD

**Issue by KuiMing** [suensummit/RCourseBankSinoPac#2]
第229行

```
raw <- readLines(filename, n = 10, encoding = "BIG-5")
```

在windows 8.1執行，只會讀到第一行，並出現以下訊息

Warning message:
In readLines("29010.xls", n = 10, encoding = "BIG-5") :
  incomplete final line found on '29010.xls'

**Comment by suensummit** [comment]
收到，晚點來解，感謝 @KuiMing
